### ISSUE TITLE
installing nosse branch on MacBook Pro M2 Max fails? 

### ISSUE THREAD

**Issue by tburcham-alidabio** [jfjlaros/tssv#5]
We have been using tssv quite successfully on our MacBook Pro M1 Pro. But we are trying to install it on a new MacBook Pro M2 Max (Ventura 13.2) and we get a failure.
This is procedure we used to install it:
1. git clone https://github.com/jfjlaros/tssv.git
2. cd newly created tssv
3. git switch nosse
4. pip3 install .
5. (Output from pip3 install attached)
6.  Try importing into python3
Successfully installed tssv-1.2.0
tim@alidamac02 tssv % python3
Python 3.10.10 (v3.10.10:aad5f6a891, Feb  7 2023, 08:47:40) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more informatio
>>> import tssv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tim/code/tssv/tssv/__init__.py", line 5, in <module>
    from .align_pair import align_pair
  File "/Users/tim/code/tssv/tssv/align_pair.py", line 1, in <module>
    from .sg_align import align
ModuleNotFoundError: No module named 'tssv.sg_align'
[tssv_install.txt](https://github.com/jfjlaros/tssv/files/10807549/tssv_install.txt)

**Comment by jfjlaros** [comment]
It looks like the installation procedure did not compile the C code. Can you remove the `build` folder (if it exists at all) and share the output of the following command?

```bash
python setup.py build
```

**Comment by tburcham-alidabio** [comment]
Here you go...

tim@alidamac0 tssv % rm -rf build
tim@alidamac0 tssv % python3 setup.py build
running build
running build_py
creating build
creating build/lib.macosx-12-arm64-cpython-310
creating build/lib.macosx-12-arm64-cpython-310/tssv
copying tssv/tssv.py -> build/lib.macosx-12-arm64-cpython-310/tssv
copying tssv/__init__.py -> build/lib.macosx-12-arm64-cpython-310/tssv
copying tssv/align_pair.py -> build/lib.macosx-12-arm64-cpython-310/tssv
copying tssv/cli.py -> build/lib.macosx-12-arm64-cpython-310/tssv
creating build/lib.macosx-12-arm64-cpython-310/tssv_extras
copying extras/annotate/annotate.py -> build/lib.macosx-12-arm64-cpython-310/tssv_extras
copying tssv/sgAlign.h -> build/lib.macosx-12-arm64-cpython-310/tssv
running build_ext
building 'tssv.sg_align' extension
creating build/temp.macosx-12-arm64-cpython-310
creating build/temp.macosx-12-arm64-cpython-310/tssv
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c tssv/sgAlign.c -o build/temp.macosx-12-arm64-cpython-310/tssv/sgAlign.o -O3
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c tssv/sgAlignWrapper.c -o build/temp.macosx-12-arm64-cpython-310/tssv/sgAlignWrapper.o -O3
clang -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk build/temp.macosx-12-arm64-cpython-310/tssv/sgAlign.o build/temp.macosx-12-arm64-cpython-310/tssv/sgAlignWrapper.o -o build/lib.macosx-12-arm64-cpython-310/tssv/sg_align.cpython-310-darwin.so
ld: warning: -undefined dynamic_lookup may not work with chained fixups

**Comment by tburcham-alidabio** [comment]
oops, sorry, that was for the M1 Pro Mac, this is for the M2 Max Mac:

tim@alidamac03 tssv % rm -rf build
tim@alidamac03 tssv % python3 setup.py build
running build
running build_py
creating build
creating build/lib.macosx-10.9-universal2-cpython-310
creating build/lib.macosx-10.9-universal2-cpython-310/tssv
copying tssv/tssv.py -> build/lib.macosx-10.9-universal2-cpython-310/tssv
copying tssv/__init__.py -> build/lib.macosx-10.9-universal2-cpython-310/tssv
copying tssv/align_pair.py -> build/lib.macosx-10.9-universal2-cpython-310/tssv
copying tssv/cli.py -> build/lib.macosx-10.9-universal2-cpython-310/tssv
creating build/lib.macosx-10.9-universal2-cpython-310/tssv_extras
copying extras/annotate/annotate.py -> build/lib.macosx-10.9-universal2-cpython-310/tssv_extras
copying tssv/sgAlign.h -> build/lib.macosx-10.9-universal2-cpython-310/tssv
running build_ext
building 'tssv.sg_align' extension
creating build/temp.macosx-10.9-universal2-cpython-310
creating build/temp.macosx-10.9-universal2-cpython-310/tssv
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c tssv/sgAlign.c -o build/temp.macosx-10.9-universal2-cpython-310/tssv/sgAlign.o -O3
clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/Library/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c tssv/sgAlignWrapper.c -o build/temp.macosx-10.9-universal2-cpython-310/tssv/sgAlignWrapper.o -O3
clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -g build/temp.macosx-10.9-universal2-cpython-310/tssv/sgAlign.o build/temp.macosx-10.9-universal2-cpython-310/tssv/sgAlignWrapper.o -o build/lib.macosx-10.9-universal2-cpython-310/tssv/sg_align.cpython-310-darwin.so

**Comment by jfjlaros** [comment]
That looks okay. What happens when you do a subsequent

```bash
python setup.py install
```

If this works, then I guess there must be something wrong with the installation procedure. There are some deprecation warnings and a complaint about a missing package.

**Comment by tburcham-alidabio** [comment]
Here you go... (I think looks OK)

tim@alidamac03 tssv % python3 setup.py install
running install
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing tssv.egg-info/PKG-INFO
writing dependency_links to tssv.egg-info/dependency_links.txt
writing entry points to tssv.egg-info/entry_points.txt
writing requirements to tssv.egg-info/requires.txt
writing top-level names to tssv.egg-info/top_level.txt
reading manifest file 'tssv.egg-info/SOURCES.txt'
adding license file 'LICENSE.md'
writing manifest file 'tssv.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-universal2/egg
running install_lib
running build_py
running build_ext
creating build/bdist.macosx-10.9-universal2
creating build/bdist.macosx-10.9-universal2/egg
creating build/bdist.macosx-10.9-universal2/egg/tssv_extras
copying build/lib.macosx-10.9-universal2-cpython-310/tssv_extras/annotate.py -> build/bdist.macosx-10.9-universal2/egg/tssv_extras
creating build/bdist.macosx-10.9-universal2/egg/tssv
copying build/lib.macosx-10.9-universal2-cpython-310/tssv/sg_align.cpython-310-darwin.so -> build/bdist.macosx-10.9-universal2/egg/tssv
copying build/lib.macosx-10.9-universal2-cpython-310/tssv/tssv.py -> build/bdist.macosx-10.9-universal2/egg/tssv
copying build/lib.macosx-10.9-universal2-cpython-310/tssv/__init__.py -> build/bdist.macosx-10.9-universal2/egg/tssv
copying build/lib.macosx-10.9-universal2-cpython-310/tssv/align_pair.py -> build/bdist.macosx-10.9-universal2/egg/tssv
copying build/lib.macosx-10.9-universal2-cpython-310/tssv/cli.py -> build/bdist.macosx-10.9-universal2/egg/tssv
copying build/lib.macosx-10.9-universal2-cpython-310/tssv/sgAlign.h -> build/bdist.macosx-10.9-universal2/egg/tssv
byte-compiling build/bdist.macosx-10.9-universal2/egg/tssv_extras/annotate.py to annotate.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/tssv/tssv.py to tssv.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/tssv/__init__.py to __init__.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/tssv/align_pair.py to align_pair.cpython-310.pyc
byte-compiling build/bdist.macosx-10.9-universal2/egg/tssv/cli.py to cli.cpython-310.pyc
creating stub loader for tssv/sg_align.cpython-310-darwin.so
byte-compiling build/bdist.macosx-10.9-universal2/egg/tssv/sg_align.py to sg_align.cpython-310.pyc
creating build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying tssv.egg-info/PKG-INFO -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying tssv.egg-info/SOURCES.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying tssv.egg-info/dependency_links.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying tssv.egg-info/entry_points.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying tssv.egg-info/requires.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
copying tssv.egg-info/top_level.txt -> build/bdist.macosx-10.9-universal2/egg/EGG-INFO
writing build/bdist.macosx-10.9-universal2/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
tssv.__pycache__.sg_align.cpython-310: module references __file__
creating dist
creating 'dist/tssv-1.2.0-py3.10-macosx-10.9-universal2.egg' and adding 'build/bdist.macosx-10.9-universal2/egg' to it
removing 'build/bdist.macosx-10.9-universal2/egg' (and everything under it)
Processing tssv-1.2.0-py3.10-macosx-10.9-universal2.egg
creating /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tssv-1.2.0-py3.10-macosx-10.9-universal2.egg
Extracting tssv-1.2.0-py3.10-macosx-10.9-universal2.egg to /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Adding tssv 1.2.0 to easy-install.pth file
Installing tannotate script to /Library/Frameworks/Python.framework/Versions/3.10/bin
Installing tssv script to /Library/Frameworks/Python.framework/Versions/3.10/bin

Installed /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tssv-1.2.0-py3.10-macosx-10.9-universal2.egg
Processing dependencies for tssv==1.2.0
Searching for xopen==1.7.0
Best match: xopen 1.7.0
Adding xopen 1.7.0 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for requests==2.28.2
Best match: requests 2.28.2
Adding requests 2.28.2 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for biopython==1.81
Best match: biopython 1.81
Adding biopython 1.81 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for certifi==2022.12.7
Best match: certifi 2022.12.7
Adding certifi 2022.12.7 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for urllib3==1.26.14
Best match: urllib3 1.26.14
Adding urllib3 1.26.14 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for idna==3.4
Best match: idna 3.4
Adding idna 3.4 to easy-install.pth file

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for charset-normalizer==3.0.1
Best match: charset-normalizer 3.0.1
Adding charset-normalizer 3.0.1 to easy-install.pth file
Installing normalizer script to /Library/Frameworks/Python.framework/Versions/3.10/bin

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Searching for numpy==1.24.2
Best match: numpy 1.24.2
Adding numpy 1.24.2 to easy-install.pth file
Installing f2py script to /Library/Frameworks/Python.framework/Versions/3.10/bin
Installing f2py3 script to /Library/Frameworks/Python.framework/Versions/3.10/bin
Installing f2py3.10 script to /Library/Frameworks/Python.framework/Versions/3.10/bin

Using /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Finished processing dependencies for tssv==1.2.0

**Comment by jfjlaros** [comment]
After this, both the CLI and the programming library work?

**Comment by tburcham-alidabio** [comment]
Does not seem to find modules imported on a relative path -- or let me know if I am doing something wrong!

tim@alidamac03 tssv % python3 cli.py --help
Traceback (most recent call last):
  File "/Users/tim/code/tssv/tssv/cli.py", line 5, in <module>
    from . import usage, version
ImportError: attempted relative import with no known parent package
tim@alidamac03 tssv % python3 tssv.py --help
Traceback (most recent call last):
  File "/Users/tim/code/tssv/tssv/tssv.py", line 10, in <module>
    from .align_pair import align_pair
ImportError: attempted relative import with no known parent package

**Comment by jfjlaros** [comment]
If you have installed it in a virtual environment, then simply running

```bash
tssv
```

should do the trick. Otherwise you could try to run

```bash
python -m tssv.cli
```

from the root of the repository.

**Comment by tburcham-alidabio** [comment]
THAT seems to work:

tim@alidamac03 tssv % tssv --help
usage: tssv [-h] [-m THRESHOLD] [-M MISMATCHES] [-n INDEL_SCORE] [-r REPORT_HANDLE] [-j] [-d PATH] [-a MINIMUM] [-v] INPUT LIBRARY

Targeted characterisation of short structural variation.

positional arguments:
  INPUT             a FASTA/FASTQ file
  LIBRARY           library of flanking sequences

options:
  -h, --help        show this help message and exit
  -m THRESHOLD      mismatches per nucleotide (default=0.08)
  -M MISMATCHES     fixed number of mismatches, overrides -m (default=None)
  -n INDEL_SCORE    insertions and deletions are penalised this number of times more heavily than mismatches (default=1)
  -r REPORT_HANDLE  name of the report file
  -j                use json format for the output file
  -d PATH           output directory
  -a MINIMUM        minimum count per allele (default=0)
  -v                show program's version number and exit

Copyright (c) Jeroen F.J. Laros <J.F.J.Laros@lumc.nl>
tim@alidamac03 tssv % which tssv
/Library/Frameworks/Python.framework/Versions/3.10/bin/tssv

**Comment by jfjlaros** [comment]
Good to hear, but it means that the installation procedure is broken.

I will read up on the latest packaging guidelines. Would you mind running a few tests if I find a proper solution?

**Comment by tburcham-alidabio** [comment]
absolutely -- would love to help
